name: detect_text_exam
data:
  file: data/exam.tsv
  input:
    image: url
  output:
    result: bool
interface:
  prompt: Does the diagram contain text, letters or numbers?
training:
  setup:
    private_name: Training for exam
    shuffle_tasks_in_task_suite: false
    assignment_max_duration_seconds: 300
    training_tasks_in_task_suite_count: 5
    inherited_instructions: true
  data:
    file: data/training.tsv
    input:
      image: url
    output:
      result: bool
project:
  setup:
    public_name: "[QA TEST EXAM] Check if an image contains text, letters or numbers"
    public_description: Look at diagrams from science textbooks and state if they
      contain text, letters or numbers.
  instructions: data/instructions.html
pool:
  exam:
    history_size: 13
    min_answers: 13
    max_performers: 3
  setup:
    private_name: Exam for detecting text
    reward_per_assignment: 0.1
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 0
    golden_tasks_count: 5
    training_tasks_count: 0
  training:
    training_passing_skill_value: 70
  filter:
  skill:
    name: Classify images
    language: EN
    description: Has been trained and and taken an exam in image classification
    hidden: true
quality_control:
  fast_responses:
    history_size: 5
    count: 3
    threshold: 2
    ban_duration: 7
    ban_units: DAYS
  skipped_assignments:
    count: 3
    ban_duration: 7
    ban_units: DAYS
  redo_banned:
  captcha:
    frequency: HIGH
    success_rate: 100
    ban_duration: 7
    ban_units: DAYS
