name: outline_text                  # Name of the pool: this is how pools and actions refer to each other
data:
  input:                            # Input data types
    image: url
  output:                           # Output data types
    outlines: json
actions:                            # Actions: what to do to tasks next
  on_submitted: verify_outlines     # All tasks get forwarded to the verification pool
  on_rejected: outline_text         # If task gets rejected in the verification pool, it gets re-added to the original pool
interface:
  prompt: Read the instructions first. Then outline all diagram elements that contain
    text, letters or numbers.
project:
  setup:
    public_name: 2 Outline text, letters or numbers in diagrams for verification
    public_description: Look at diagrams from science textbooks and state if they
      contain text, letters or numbers.
  instructions: data/instructions.html       # Task instructions in an HTML file
training:
pool:
  setup:
    private_name: Outline text
    reward_per_assignment: 0.1
    assignment_max_duration_seconds: 600
    auto_accept_solutions: false             # Submitted tasks are not accepted automatically
    auto_accept_period_day: 3                # Tasks are automatically accepted after three days
  defaults:
    default_overlap_for_new_tasks: 1        # Overlap for pool: how many performers need to do the task
    default_overlap_for_new_task_suites: 1  # Overlap for pool: how many performers need to do the task suite
  mixer:
    real_tasks_count: 1                     # How many real tasks in a taks suite
    golden_tasks_count: 0                   # How many control tasks in a task suite 
    training_tasks_count: 0                 # How many training tasks in a task suite
  filter:                                   # Specify filters: only allow some performers to see the pool
    languages:
    - EN                                    # Only English speakers see the pool
    client_type:                            # Only people using the Toloka app or browser see the pool
    - TOLOKA_APP
    - BROWSER
