name: classify_text
data:
  file: data/text_data.tsv
  input:
    text: str
  output:
    result: str
options:
  positive: Positive
  negative: Negative
  neutral: Neutral
interface:
  prompt: Read the text and assign it to the most appropriate category.
project:
  setup:
    public_name: Classify text into categories
    public_description: Read the text and assign it to the most appropriate category.
  instructions: data/instructions.html
training:
pool:
  estimated_time_per_suite: 60
  setup:
    private_name: Classify text
    reward_per_assignment: 0.2
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 3
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    languages:
    - EN
    client_type:
    - TOLOKA_APP
    - BROWSER