name: verify_outlines
data:
  input:
    image: url
    outlines: json
  output:
    result: bool
actions:
  on_accepted: process_result
interface:
  prompt: Read the instructions first. Is the diagram annotated according to the instructions?
project:
  id: 94594
  setup:
    public_name: Verify outlines for text, letters or numbers in diagrams
    public_description: Look at diagrams from science textbooks and verify if they have
      been annotated correctly.
  instructions: data/instructions.html
training:
pool:
  id: 1093920
  setup:
    private_name: Verify outlines
    reward_per_assignment: 0.1
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    languages:
    - EN
    client_type:
    - BROWSER
