name: forward_verify
data: result
on_result:
  correct:
    - accept
    - separate_bboxes
  incorrect: reject
  human_error:
    - accept
    - fix_outlines
messages:
  correct: "The outlines were evaluated as correct."
  incorrect: "The outlines were evaluated as incorrect."
  human_error: "The outlines were evaluated as correct, although they contained human errors. You will be paid for the work."
