name: aggregate_verify
source: verify_outlines   # Pool from which tasks are forwarded to the Aggregate-action
actions:                  # What happens to tasks after aggregation
  on_result: forward_verify
method: dawid_skene       # Aggregation method. For options, see https://toloka.ai/en/docs/crowd-kit/
                          # For now, methods for categorical responses are supported