name: annotate_text
data:
  file: data/classify_text_data.tsv
  input:
    text: str
  output:
    annotations: json
interface:
  prompt: Annotate verbs, nouns and adjectives in the text below.
  labels:
    verb: Verb
    noun: Noun
    adj: Adjective
project:
  setup:
    public_name: Annotate texts for word classes
    public_description: Annotate texts for word classes.
  instructions: instructions/classify_text_instructions.html
pool:
  estimated_time_per_suite: 60
  setup:
    private_name: Classify text
    reward_per_assignment: 0.2
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    languages:
      - EN