name: classify_text
data:
  file: data/classify_text_data.tsv
  input:
    text: str
  output:
    result: str
interface:
  prompt: Read the text and classify its sentiment.
  labels:
    positive: Positive
    negative: Negative
    neutral: Neutral
project:
  setup:
    public_name: Classify the sentiment of texts
    public_description: Read the text and classify its sentiment.
  instructions: instructions/classify_text_instructions.html
pool:
  estimated_time_per_suite: 60
  setup:
    private_name: Classify text
    reward_per_assignment: 0.2
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 3
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    languages:
      - EN
    #skill:
      # CONFIGURE THE SKILL ID PRODUCED BY YOUR EXAM AND THE EXPECTED SKILL VALUE HERE. For example:
      # 12345: 80