name: outline_text
data:
  file: data/verify_image_data.tsv
  input:
    image: url
  output:
    outlines: json
actions:
  on_submitted: verify_polygon
  on_rejected: outline_text
interface:
  prompt: Read the instructions first. Then outline all diagram elements that contain
    text, letters or numbers.
project:
  id: 137771
  setup:
    public_name: Outline text, letters or numbers in diagrams
    public_description: Look at diagrams from science textbooks and state if they
      contain text, letters or numbers.
  instructions: instructions/outline_text_instructions.html
training:
pool:
  estimated_time_per_suite: 120
  setup:
    private_name: Outline text
    reward_per_assignment: 0.4
    assignment_max_duration_seconds: 600
    auto_accept_solutions: false
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    languages:
    - EN
    client_type:
    - TOLOKA_APP
    - BROWSER
quality_control:
  fast_responses:
    history_size: 5
    count: 3
    threshold: 2
    ban_duration: 7
    ban_units: DAYS
  skipped_assignments:
    count: 3
    ban_duration: 7
    ban_units: DAYS
  redo_banned: true

