name: verify_outlines
data:
  input:
    image: url                          
    outlines: json
  output:
    result: str
actions:
  on_closed: aggregate_verify
interface:
  prompt: Read the instructions first. Is the diagram annotated according to the instructions?
  verification: true
  labels:
    correct: "Yes"
    incorrect: "No"
    human_error: "Human error"
project:
  setup:
    public_name: Verify outlines for text, letters or numbers in diagrams
    public_description: Look at diagrams from science textbooks and verify if they have
      been annotated correctly.
  instructions: instructions/verify_outlines_instructions.html
training:
pool:
  estimated_time_per_suite: 15
  setup:
    private_name: Verify outlines
    reward_per_assignment: 0.075
    assignment_max_duration_seconds: 600
    auto_accept_solutions: true
  defaults:
    default_overlap_for_new_tasks: 1
    default_overlap_for_new_task_suites: 1
  mixer:
    real_tasks_count: 1
    golden_tasks_count: 0
    training_tasks_count: 0
  filter:
    languages:          
    - EN
    client_type:
    - BROWSER
    - TOLOKA_APP
quality_control:
  speed_quality_balance:
    top_percentage_by_quality: 40
  fast_responses:
    history_size: 5
    count: 3
    threshold: 2
    ban_duration: 7
    ban_units: DAYS
  skipped_assignments:
    count: 3
    ban_duration: 7
    ban_units: DAYS
  redo_banned: true
